# Generated by Django 2.1.5 on 2019-01-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20181028_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='mm',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
