# Generated by Django 2.1.5 on 2019-01-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_album_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='mm',
        ),
    ]
