# Generated by Django 2.1.5 on 2019-01-28 19:11

from django.db import migrations, models
import example.models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_remove_album_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mp3',
            field=models.FileField(upload_to=example.models.update_filename),
        ),
    ]
